### ISSUE TITLE
Need pull request for comments

### ISSUE THREAD

**Issue by vinniefalco** [Hefting/HarmonIQ#3]
I'd like to comment on the changes in this commit:
https://github.com/Hefting/HarmonIQ/commit/7acf40b3ae250f6708c1e636dc82656c75b69046

In order to do so, the commit needs to be part of a pull request against a branch that does not contain the commit. If this gets set up, I'll be able to comment.

**Comment by Hefting** [comment]
I see you've already added some comments. Thanks for that!

Did you manage to write all notes in it or are do you still need a pull request?

**Comment by vinniefalco** [comment]
I only did a light examination, because GitHub loses comments on any code change. There are some issues with the management of the lifetime of the sessions in the code I saw - this is a very common problem in asynchronous code. I suggest you study the async websocket echo server in the Beast test directory very carefully, there are a lot of subtle differences between that code and yours.

**Comment by Hefting** [comment]
Thanks for the suggestions. The problems in my asynchronous code start to click, including [your comment](https://github.com/Hefting/HarmonIQ/commit/7acf40b3ae250f6708c1e636dc82656c75b69046#commitcomment-18546829) about ownership of `shared_ptr<WebSocketSession>` and its lifetime management. I will dive into the test code and update you later.

**Comment by Hefting** [comment]
I have done lots of refactoring and created a [pull request](https://github.com/Hefting/HarmonIQ/pull/4) with all changes since I started implementing WebSockets using Beast. From testing it and playing around with it, the implementation seems to work.

If it's not too much effort, could you maybe take one last look at it? That would be great. It's about:
 - WebSocketAcceptor [.hpp](https://github.com/Hefting/HarmonIQ/pull/4/files#diff-47afb847e038634b754998f45f785768) / [.cpp](https://github.com/Hefting/HarmonIQ/pull/4/files#diff-7fa93f1a176d905e33971e7b5ec79015)
 - WebSocketSession [.hpp](https://github.com/Hefting/HarmonIQ/pull/4/files#diff-847bc6dc00d30c832261997f9b081fb0) / [.cpp](https://github.com/Hefting/HarmonIQ/pull/4/files#diff-949df85233b83df370a940a5e4ab742e)
